-- =============================================
-- LUMINA INTERACTIVE™ — SUPABASE SCHEMA
-- Execute no SQL Editor do Supabase
-- =============================================

-- Tabela de produtos
create table if not exists produtos (
  id bigint generated by default as identity primary key,
  nome text not null,
  slug text unique,
  categoria text,
  descricao text,
  preco numeric default 0,
  imagem text,
  ativo boolean default true,
  criado_em timestamp with time zone default now()
);

-- Tabela de pedidos (completa com todos os campos usados no admin)
create table if not exists pedidos (
  id bigint generated by default as identity primary key,
  nome_cliente text,
  email text,
  whatsapp text,
  produto text,
  plano text,
  valor numeric default 0,
  status text default 'pendente',
  metodo_pagamento text,
  acesso_liberado boolean default false,
  download_url text,
  comprovante_url text,
  data_pagamento timestamp with time zone,
  data_fim timestamp with time zone,
  criado_em timestamp with time zone default now()
);

-- Tabela de notícias
create table if not exists noticias (
  id bigint generated by default as identity primary key,
  titulo text,
  texto text,
  imagem text,
  publicado boolean default true,
  criado_em timestamp with time zone default now()
);

-- Tabela de downloads padrão (usada pelo admin para aprovação automática)
create table if not exists downloads_padrao (
  id bigint generated by default as identity primary key,
  produto text,
  versao text,
  download_url text,
  ativo boolean default true,
  criado_em timestamp with time zone default now()
);

-- Tabela de downloads (histórico público)
create table if not exists downloads (
  id bigint generated by default as identity primary key,
  produto text,
  versao text,
  link text,
  changelog text,
  ativo boolean default true,
  criado_em timestamp with time zone default now()
);

-- Produtos padrão
insert into produtos (nome, slug, categoria, descricao, preco, ativo)
values
  ('Brazukas Patch', 'brazukas',    'Patch',      'O patch brasileiro definitivo para PES PSP.', 0,    true),
  ('LPFL Normal',    'lpfl-normal', 'Patch',      'A experiência clássica do futebol portátil.', 0,    true),
  ('LPFL PRO',       'lpfl-pro',    'Patch Premium', 'A versão premium com visual e conteúdo avançado.', 0, true),
  ('Lumina Plus',    'lumina-plus', 'Assinatura', 'Acesso premium da Lumina Interactive.',       9.90, true)
on conflict (slug) do nothing;

-- Políticas RLS recomendadas (ajuste conforme necessidade)
-- alter table pedidos enable row level security;
-- create policy "Usuários veem próprios pedidos" on pedidos
--   for select using (auth.jwt() ->> 'email' = email);
