-- LUMINA INTERACTIVE™ SUPABASE SCHEMA

create table if not exists produtos (
  id bigint generated by default as identity primary key,
  nome text not null,
  slug text unique,
  categoria text,
  descricao text,
  preco numeric default 0,
  imagem text,
  ativo boolean default true,
  criado_em timestamp with time zone default now()
);

create table if not exists pedidos (
  id bigint generated by default as identity primary key,
  nome_cliente text,
  email text,
  whatsapp text,
  produto text,
  plano text,
  valor numeric default 0,
  status text default 'pendente',
  metodo_pagamento text,
  criado_em timestamp with time zone default now()
);

create table if not exists noticias (
  id bigint generated by default as identity primary key,
  titulo text,
  texto text,
  imagem text,
  publicado boolean default true,
  criado_em timestamp with time zone default now()
);

create table if not exists downloads (
  id bigint generated by default as identity primary key,
  produto text,
  versao text,
  link text,
  changelog text,
  ativo boolean default true,
  criado_em timestamp with time zone default now()
);

insert into produtos (nome, slug, categoria, descricao, preco, ativo)
values
('Brazukas Patch', 'brazukas', 'Patch', 'O patch brasileiro definitivo para PES PSP.', 0, true),
('LPFL Normal', 'lpfl-normal', 'Patch', 'A experiência clássica do futebol portátil.', 0, true),
('LPFL PRO', 'lpfl-pro', 'Patch Premium', 'A versão premium com visual e conteúdo avançado.', 0, true),
('Lumina Plus', 'lumina-plus', 'Assinatura', 'Acesso premium da Lumina Interactive.', 9.90, true)
on conflict (slug) do nothing;
